version: '3.8'
services:
  dev_env:
    build:
      # CHANGE 1: Use a single dot "." (This is CampaignStudio folder)
      context: .
      dockerfile: .devcontainer/Dockerfile.toolbox
    volumes:
      # CHANGE 2: Use a single dot "." (Mount CampaignStudio)
      - .:/workspaces/CampaignStudio:cached
    command: sleep infinity
    network_mode: service:db